import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';

import {
  appendGeneratedFilesToGitignore,
  derivedWorkerVars,
  loadOptionalManifest,
  mergeDecision,
  parseEnv,
  proxyEntriesFromFiles,
  renderManifest,
  runtimeEntriesFromFiles,
  writeGeneratedFiles
} from '../../scripts/lib/cloudflare-config.mjs';

function tempDir() {
  return mkdtempSync(join(tmpdir(), 'cloudflare-sandbox-test-'));
}

test('parseEnv reads simple dotenv files', () => {
  const values = parseEnv(`
    SAFE=value
    QUOTED="hello world"
    SINGLE='one two'
    # ignored
  `);

  assert.equal(values.get('SAFE'), 'value');
  assert.equal(values.get('QUOTED'), 'hello world');
  assert.equal(values.get('SINGLE'), 'one two');
});

test('mergeDecision uses Cloudflare defaults for known providers', () => {
  assert.deepEqual(mergeDecision('OPENAI_API_KEY'), {
    name: 'OPENAI_API_KEY',
    mode: 'proxy_secret',
    provider: 'openai',
    host: 'api.openai.com',
    networkUrl: 'api.openai.com:443'
  });

  assert.deepEqual(mergeDecision('R2_SECRET_ACCESS_KEY'), {
    name: 'R2_SECRET_ACCESS_KEY',
    mode: 'signing_secret',
    service: 'r2'
  });

  assert.deepEqual(mergeDecision('REQUEST_TIMEOUT_SECONDS'), {
    name: 'REQUEST_TIMEOUT_SECONDS',
    mode: 'runtime_env'
  });
});

test('writeGeneratedFiles separates runtime env from Worker-side secrets', () => {
  const dir = tempDir();
  try {
    const manifest = {
      workspace: { appPath: '.', repoUrl: 'https://github.com/org/repo.git' },
      variables: [
        { name: 'REQUEST_TIMEOUT_SECONDS', mode: 'runtime_env' },
        { name: 'OPENAI_API_KEY', mode: 'proxy_secret', provider: 'openai' },
        { name: 'R2_SECRET_ACCESS_KEY', mode: 'signing_secret', service: 'r2' }
      ]
    };
    const envValues = new Map([
      ['REQUEST_TIMEOUT_SECONDS', '30'],
      ['OPENAI_API_KEY', 'sk-real'],
      ['R2_SECRET_ACCESS_KEY', 'r2-real']
    ]);

    writeGeneratedFiles(dir, manifest, envValues);

    assert.equal(readFileSync(join(dir, 'cloudflare-runtime.env'), 'utf8'), 'REQUEST_TIMEOUT_SECONDS=30\n');
    assert.equal(
      readFileSync(join(dir, 'cloudflare-proxy-secrets.env'), 'utf8'),
      'OPENAI_API_KEY=sk-real\nR2_SECRET_ACCESS_KEY=r2-real\n'
    );
    const loaded = loadOptionalManifest(join(dir, 'cloudflare-sandbox.toml'));
    assert.equal(loaded.workspace.repoUrl, 'https://github.com/org/repo.git');
    assert.equal(loaded.variables.length, 3);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('runtimeEntriesFromFiles and proxyEntriesFromFiles load generated env files', () => {
  const dir = tempDir();
  try {
    writeFileSync(join(dir, 'cloudflare-runtime.env'), 'A=1\nB="two words"\n');
    writeFileSync(join(dir, 'cloudflare-proxy-secrets.env'), 'SECRET=s3\n');

    assert.deepEqual(runtimeEntriesFromFiles(dir), { A: '1', B: 'two words' });
    assert.deepEqual(proxyEntriesFromFiles(dir), { SECRET: 's3' });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('appendGeneratedFilesToGitignore appends missing generated Cloudflare files', () => {
  const dir = tempDir();
  try {
    writeFileSync(join(dir, '.gitignore'), '.env\n');
    const message = appendGeneratedFilesToGitignore(dir);

    assert.match(message, /append/);
    const gitignore = readFileSync(join(dir, '.gitignore'), 'utf8');
    assert.match(gitignore, /cloudflare-runtime\.env/);
    assert.match(gitignore, /cloudflare-proxy-secrets\.env/);
    assert.match(gitignore, /cloudflare-sandbox\.toml/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('renderManifest uses non-secret setup decisions', () => {
  const rendered = renderManifest({
    workspace: { appPath: '.', branch: 'main' },
    variables: [{ name: 'OPENAI_API_KEY', mode: 'proxy_secret', provider: 'openai' }]
  });

  assert.match(rendered, /Generated by setup-cloudflare-sandbox/);
  assert.match(rendered, /name = "OPENAI_API_KEY"/);
  assert.doesNotMatch(rendered, /sk-/);
});

test('derivedWorkerVars writes allowed hosts for provider and R2 egress', () => {
  const entries = derivedWorkerVars(
    {
      variables: [
        {
          name: 'OPENAI_API_KEY',
          mode: 'proxy_secret',
          networkUrl: 'api.openai.com:443'
        }
      ]
    },
    new Map([
      ['R2_ACCOUNT_ID', 'acct123'],
      ['R2_BUCKET_NAME', 'bucket-name']
    ])
  );

  assert.deepEqual(entries, [[
    'CF_SANDBOX_ALLOWED_HOSTS',
    'api.openai.com,acct123.r2.cloudflarestorage.com,bucket-name.acct123.r2.cloudflarestorage.com'
  ]]);
});
