from __future__ import annotations

from pathlib import Path
import tomllib

from setup_docker_sandbox.models import Decision, Mode, Scope


def toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_manifest(path: Path, decisions: list[Decision]) -> None:
    lines = [
        "# Generated by setup-docker-sandbox.",
        "# This file stores setup decisions only. It must not contain secret values.",
        "",
    ]

    for decision in decisions:
        if decision.mode is Mode.SKIP:
            continue
        lines.extend(
            [
                "[[variables]]",
                f"name = {toml_string(decision.name)}",
                f"mode = {toml_string(decision.mode.value)}",
                f"scope = {toml_string(decision.scope.value)}",
            ]
        )
        if decision.service:
            lines.append(f"service = {toml_string(decision.service)}")
        if decision.host:
            lines.append(f"host = {toml_string(decision.host)}")
        if decision.registry:
            lines.append(f"registry = {toml_string(decision.registry)}")
        if decision.username:
            lines.append(f"username = {toml_string(decision.username)}")
        if decision.network_url:
            lines.append(f"network_url = {toml_string(decision.network_url)}")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def load_manifest(path: Path) -> dict[str, Decision]:
    if not path.exists():
        return {}

    data = tomllib.loads(path.read_text(encoding="utf-8"))
    decisions: dict[str, Decision] = {}
    for item in data.get("variables", []):
        if not isinstance(item, dict):
            continue
        name = item.get("name")
        mode = item.get("mode")
        if not isinstance(name, str) or not isinstance(mode, str):
            continue

        try:
            parsed_mode = Mode(mode)
        except ValueError:
            continue

        scope_value = item.get("scope", Scope.SANDBOX.value)
        try:
            parsed_scope = Scope(scope_value)
        except ValueError:
            parsed_scope = Scope.SANDBOX

        decisions[name] = Decision(
            name=name,
            value="",
            mode=parsed_mode,
            scope=parsed_scope,
            sandbox_name=None,
            service=item.get("service"),
            host=item.get("host"),
            registry=item.get("registry"),
            username=item.get("username"),
            network_url=item.get("network_url"),
        )
    return decisions
