from __future__ import annotations

from pathlib import Path

from setup_docker_sandbox.models import Decision, Mode


def toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_manifest(path: Path, decisions: list[Decision]) -> None:
    lines = [
        "# Generated by setup-docker-sandbox.",
        "# This file stores setup decisions only. It must not contain secret values.",
        "",
    ]

    for decision in decisions:
        if decision.mode is Mode.SKIP:
            continue
        lines.extend(
            [
                "[[variables]]",
                f"name = {toml_string(decision.name)}",
                f"mode = {toml_string(decision.mode.value)}",
                f"scope = {toml_string(decision.scope.value)}",
            ]
        )
        if decision.sandbox_name:
            lines.append(f"sandbox_name = {toml_string(decision.sandbox_name)}")
        if decision.service:
            lines.append(f"service = {toml_string(decision.service)}")
        if decision.host:
            lines.append(f"host = {toml_string(decision.host)}")
        if decision.registry:
            lines.append(f"registry = {toml_string(decision.registry)}")
        if decision.username:
            lines.append(f"username = {toml_string(decision.username)}")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
