import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const TOOL_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

const GENERATED_FILES = [
  'cloudflare-runtime.env',
  'cloudflare-proxy-secrets.env',
  'cloudflare-sandbox.toml'
];

function parseEnv(text) {
  const values = new Map();
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;
    values.set(match[1], parseEnvValue(match[2]));
  }
  return values;
}

function parseEnvValue(raw) {
  let value = raw.trim();
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    value = value.slice(1, -1);
  }
  return value.replace(/\\n/g, '\n');
}

function renderEnv(entries) {
  return `${entries
    .map(([name, value]) => `${name}=${quoteEnvValue(value)}`)
    .join('\n')}\n`;
}

function quoteEnvValue(value) {
  if (/^[A-Za-z0-9_./:@-]*$/.test(value)) return value;
  return JSON.stringify(value);
}

function tomlQuote(value) {
  return JSON.stringify(value);
}

function renderManifest({ workspace = {}, variables = [] }) {
  const lines = [
    '# Generated by setup-cloudflare-sandbox.',
    '# This file stores setup decisions only. It must not contain secret values.',
    '',
    '[workspace]',
    `app_path = ${tomlQuote(workspace.appPath ?? '.')}`
  ];
  if (workspace.repoUrl) lines.push(`repo_url = ${tomlQuote(workspace.repoUrl)}`);
  if (workspace.branch) lines.push(`branch = ${tomlQuote(workspace.branch)}`);
  lines.push('');

  for (const variable of variables) {
    lines.push('[[variables]]');
    lines.push(`name = ${tomlQuote(variable.name)}`);
    lines.push(`mode = ${tomlQuote(variable.mode)}`);
    if (variable.provider) lines.push(`provider = ${tomlQuote(variable.provider)}`);
    if (variable.service) lines.push(`service = ${tomlQuote(variable.service)}`);
    if (variable.host) lines.push(`host = ${tomlQuote(variable.host)}`);
    if (variable.networkUrl) lines.push(`network_url = ${tomlQuote(variable.networkUrl)}`);
    lines.push('');
  }

  return lines.join('\n');
}

function parseManifest(text) {
  const manifest = { workspace: {}, variables: [] };
  let section = null;
  let currentVariable = null;

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    if (line === '[workspace]') {
      section = 'workspace';
      currentVariable = null;
      continue;
    }
    if (line === '[[variables]]') {
      section = 'variables';
      currentVariable = {};
      manifest.variables.push(currentVariable);
      continue;
    }

    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) continue;
    const key = match[1];
    const value = parseTomlString(match[2]);
    if (section === 'workspace') {
      manifest.workspace[toCamel(key)] = value;
    } else if (section === 'variables' && currentVariable) {
      currentVariable[toCamel(key)] = value;
    }
  }
  return manifest;
}

function parseTomlString(raw) {
  const value = raw.trim();
  if (value.startsWith('"')) return JSON.parse(value);
  return value;
}

function toCamel(key) {
  return key.replace(/_([a-z])/g, (_, char) => char.toUpperCase());
}

function loadEnvFile(path) {
  if (!existsSync(path)) throw new Error(`${path} does not exist`);
  return parseEnv(readFileSync(path, 'utf8'));
}

function loadOptionalEnvFile(path) {
  if (!existsSync(path)) return new Map();
  return parseEnv(readFileSync(path, 'utf8'));
}

function loadOptionalManifest(path) {
  if (!existsSync(path)) return null;
  return parseManifest(readFileSync(path, 'utf8'));
}

function writeGeneratedFiles(appDir, manifest, envValues, { dryRun = false } = {}) {
  const runtimeEntries = [];
  const proxyEntries = [];

  for (const variable of manifest.variables) {
    const value = envValues.get(variable.name);
    if (value === undefined) continue;
    if (variable.mode === 'runtime_env') runtimeEntries.push([variable.name, value]);
    if (variable.mode === 'proxy_secret' || variable.mode === 'signing_secret') {
      proxyEntries.push([variable.name, value]);
    }
  }

  const operations = [
    [`${appDir}/cloudflare-runtime.env`, renderEnv(runtimeEntries)],
    [`${appDir}/cloudflare-proxy-secrets.env`, renderEnv(proxyEntries)],
    [`${appDir}/cloudflare-sandbox.toml`, renderManifest(manifest)]
  ];

  if (!dryRun) {
    for (const [path, content] of operations) writeFileSync(path, content, 'utf8');
  }

  return operations.map(([path]) => `write ${path}`);
}

function writeDevVars(toolDir, entries, { dryRun = false } = {}) {
  const path = `${toolDir}/.dev.vars`;
  if (!dryRun) writeFileSync(path, renderEnv(entries), 'utf8');
  return `write ${path} (${entries.length} entries)`;
}

function derivedWorkerVars(manifest, envValues) {
  const entries = [];
  const allowedHosts = new Set();

  for (const variable of manifest.variables ?? []) {
    if (variable.networkUrl) allowedHosts.add(stripPort(variable.networkUrl));
  }

  const accountId = envValues.get('R2_ACCOUNT_ID');
  const bucketName = envValues.get('R2_BUCKET_NAME');
  if (accountId) allowedHosts.add(`${accountId}.r2.cloudflarestorage.com`);
  if (accountId && bucketName) {
    allowedHosts.add(`${bucketName}.${accountId}.r2.cloudflarestorage.com`);
  }

  if (allowedHosts.size) {
    entries.push(['CF_SANDBOX_ALLOWED_HOSTS', [...allowedHosts].join(',')]);
  }
  return entries;
}

function stripPort(value) {
  return value.replace(/:\d+$/, '');
}

function appendGeneratedFilesToGitignore(appDir, { dryRun = false } = {}) {
  const path = `${appDir}/.gitignore`;
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : '';
  const patterns = existing
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
  const missing = GENERATED_FILES.filter((file) => !patterns.includes(file));
  if (!missing.length) return `${path} already covers generated Cloudflare files`;
  if (!dryRun) {
    const prefix = existing && !existing.endsWith('\n') ? '\n' : '';
    appendFileSync(path, `${prefix}${missing.join('\n')}\n`, 'utf8');
  }
  return `${dryRun ? 'dry-run: append' : 'append'} ${missing.join(', ')} to ${path}`;
}

function providerDefaults(name) {
  if (name === 'OPENAI_API_KEY') {
    return { mode: 'proxy_secret', provider: 'openai', host: 'api.openai.com', networkUrl: 'api.openai.com:443' };
  }
  if (name === 'ANTHROPIC_API_KEY' || name === 'CLAUDE_CODE_OAUTH_TOKEN') {
    return { mode: 'proxy_secret', provider: 'anthropic', host: 'api.anthropic.com', networkUrl: 'api.anthropic.com:443' };
  }
  if (name === 'GITHUB_TOKEN') {
    return { mode: 'proxy_secret', provider: 'github', host: 'github.com', networkUrl: 'github.com:443' };
  }
  if (name.startsWith('R2_') || name.startsWith('AWS_')) {
    if (name.includes('SECRET') || name.includes('ACCESS_KEY')) {
      return { mode: 'signing_secret', service: 'r2' };
    }
    return { mode: 'runtime_env' };
  }
  return { mode: 'runtime_env' };
}

function mergeDecision(name, existing) {
  if (existing) return { ...existing, name };
  return { name, ...providerDefaults(name) };
}

function runtimeEntriesFromFiles(appDir) {
  const entries = loadOptionalEnvFile(`${appDir}/cloudflare-runtime.env`);
  return Object.fromEntries(entries);
}

function proxyEntriesFromFiles(appDir) {
  const entries = loadOptionalEnvFile(`${appDir}/cloudflare-proxy-secrets.env`);
  return Object.fromEntries(entries);
}

export {
  GENERATED_FILES,
  TOOL_ROOT,
  appendGeneratedFilesToGitignore,
  loadEnvFile,
  loadOptionalEnvFile,
  loadOptionalManifest,
  mergeDecision,
  parseEnv,
  parseManifest,
  proxyEntriesFromFiles,
  renderEnv,
  renderManifest,
  runtimeEntriesFromFiles,
  writeDevVars,
  derivedWorkerVars,
  writeGeneratedFiles
};
